setup: |
  echo "🐊 Attempt to install exposition engineering tools"
  echo "🐊 Using pipx to perform program installation"
  echo "🐊 Will not re-install if already installed"
  pipx install pymarkdownlnt
---

# Checks on Files {{{

# perform checks on a file
- writing/characterization/podcast_audio_identity.md:
    - description: Ensure that the podcast_audio_identity.md file exists in the writing/characterization/ directory
      check: ConfirmFileExists
    - description: Complete all TODOs, remove the TODO markers, and rewrite comments for the reflection
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true
    - description: Delete the 'Add Your Name Here' prompt in the reflection file
      check: MatchFileFragment
      options:
        fragment: "Add Your Name Here"
        count: 0
        exact: true
    - description: Retype the every word in the Honor Code pledge in reflection.md
      check: MatchFileFragment
      options:
        fragment: "I adhered to the Allegheny College Honor Code while completing this project."
        count: 3
        exact: true
    - description: Confirm that the markdown file containing the audio identity has the correct number of headers
      check: CountMarkdownTags
      options:
        tag: heading
        count: 14
        exact: true
    - description: Confirm that the markdown file containing the audio identity has the correct number of lists
      check: CountMarkdownTags
      options:
        tag: list
        count: 4
        exact: false
    - description: Confirm that the markdown file containing the audio identity has the correct number of links
      check: CountMarkdownTags
      options:
        tag: link
        count: 18
        exact: false
    - description: Confirm that the markdown file containing the audio identity has the HTML block markers
      check: CountMarkdownTags
      options:
        tag: html_block
        count: 2
        exact: false
    - description: Confirm that the markdown file containing the audio identity has a label for an audio file link
      check: MatchFileFragment
      options:
        fragment: "**Link to the Web Site that Provided/Created Your Audio**"
        count: 1
        exact: true
    - description: Confirm that the markdown file containing the audio identity has a label for a GitHub repo
      check: MatchFileFragment
      options:
        fragment: "**Link to the Audio File in Your GitHub Repository**"
        count: 1
        exact: true

# perform checks on a file
- audio/podcast_audio.mp3:
    - description: Ensure that the podcast audio file with the mp3 filename extension exists in the audio/ directory
      check: ConfirmFileExists

# }}}

# Check Output from Linters {{{

# run a check
- description: Confirm that the show characterization file passes the linting checks run by pymarkdownlnt
  command: "pymarkdown --config .pymarkdown.cfg scan writing/characterization/podcast_audio_identity.md"

# }}}

# Commits {{{

# count number of commits in the GitHub repository
- description: Have at least a specific minimum of commits in repository
  check: CountCommits
  options:
    count: 10

# }}}
